"""Filter-related dashboard tools: add, update, remove, bind, and unbind filters."""

from langchain_core.runnables import RunnableConfig
from langchain_core.tools import tool

from apps.shared.core.exceptions import ResourceNotFoundError, ValidationError
from apps.shared.dashboard.adapters import domain_filter_to_dto
from apps.shared.dashboard.domain import DashboardFilterOption
from apps.shared.dashboard.schemas import (
    DashboardFilterCreateRequest,
    DashboardFilterToolAddRequest,
    DashboardFilterToolRemoveRequest,
    DashboardFilterToolUpdateRequest,
    DashboardFilterUpdateDTO,
)
from apps.shared.dashboard.service import DashboardService
from apps.shared.data_source import AssetMetadataRepository, DataSourceRepository, DataSourceService
from apps.shared.db.session import app_db_session
from apps.shared.domain.actor import ActorContext
from apps.shared.utils.logger import get_logger
from apps.tenant_app_service.agents.context import extract_runtime_context
from apps.tenant_app_service.agents.tools.tool_result import ToolResult

logger = get_logger(__name__)


def _actor_ctx(runtime) -> ActorContext:
    return ActorContext(
        tenant_id=runtime.user.tenant_id,
        user_id=runtime.user.user_id,
        user_role=runtime.user.role,
    )


@tool(args_schema=DashboardFilterToolAddRequest)
async def add_filter_to_dashboard(
    dashboard_id: int,
    filter_data: DashboardFilterCreateRequest,
    config: RunnableConfig = None,
) -> ToolResult:
    """Add filter to dashboard. Types: time_range (SQL: $time_filter(:param_key, field)), dropdown_static/dropdown_datasource (SQL: $in_or_equal(:param_key, field)).

    Args:
        dashboard_id: Dashboard ID
        filter_data: Filter payload (create request model). ID is auto-generated by service.
        config: Runtime config

    Returns:
        JSON with dashboard_id, filter_id, message
    """
    runtime = extract_runtime_context(config)
    actor = _actor_ctx(runtime)

    async with app_db_session() as session:
        service = DashboardService.create(tenant_id=actor.tenant_id, db_session=session)
        data_source_service = DataSourceService(
            tenant_id=actor.tenant_id,
            data_source_repo=DataSourceRepository(session),
            asset_repo=AssetMetadataRepository(session),
        )
        try:
            new_filter = await service.add_filter_for_actor(
                dashboard_id=dashboard_id,
                actor=actor,
                name=filter_data.name,
                filter_type=filter_data.type,
                param_key=filter_data.param_key,
                value=filter_data.value,
                data_source_id=filter_data.data_source_id,
                options_query=filter_data.options_query,
                options=[DashboardFilterOption(label=o.label, value=o.value) for o in filter_data.options]
                if filter_data.options
                else None,
                allow_multiple=filter_data.allow_multiple,
                time_precision=filter_data.time_precision,
                description=filter_data.description,
                required=filter_data.required or False,
                validate_options_query=True,
                data_source_service=data_source_service,
            )
            return ToolResult.success(domain_filter_to_dto(new_filter).model_dump(exclude_none=True))
        except ResourceNotFoundError as e:
            return ToolResult.error_result(code="DASHBOARD_NOT_FOUND", message=str(e))
        except ValidationError as e:
            return ToolResult.error_result(code="FILTER_VALIDATION_FAILED", message=str(e))


@tool(args_schema=DashboardFilterToolUpdateRequest)
async def update_filter_on_dashboard(
    dashboard_id: int,
    filter_id: str,
    updates: DashboardFilterUpdateDTO,
    config: RunnableConfig = None,
) -> ToolResult:
    """Update filter configuration. All fields in updates DTO are optional.

    Args:
        dashboard_id: Dashboard ID
        filter_id: Filter ID to update
        updates: Update data (DTO with optional fields: name, type, param_key, value, etc.)
        config: Runtime config

    Returns:
        JSON snapshot of updated filter state
    """
    runtime = extract_runtime_context(config)
    actor = _actor_ctx(runtime)

    async with app_db_session() as session:
        service = DashboardService.create(tenant_id=actor.tenant_id, db_session=session)
        data_source_service = DataSourceService(
            tenant_id=actor.tenant_id,
            data_source_repo=DataSourceRepository(session),
            asset_repo=AssetMetadataRepository(session),
        )
        try:
            update_data = updates.model_dump(exclude_unset=True)
            # Convert DTO options list to domain objects.
            if "options" in update_data and update_data["options"] is not None:
                update_data["options"] = [DashboardFilterOption(label=o.label, value=o.value) for o in updates.options]
            updated_filter = await service.update_filter_for_actor(
                dashboard_id=dashboard_id,
                filter_id=filter_id,
                actor=actor,
                field_updates=update_data,
                validate_options_query=True,
                data_source_service=data_source_service,
            )
            return ToolResult.success(domain_filter_to_dto(updated_filter).model_dump(exclude_none=True))
        except ResourceNotFoundError as e:
            return ToolResult.error_result(code="DASHBOARD_FILTER_NOT_FOUND", message=str(e))
        except ValidationError as e:
            return ToolResult.error_result(code="FILTER_VALIDATION_FAILED", message=str(e))


@tool(args_schema=DashboardFilterToolRemoveRequest)
async def remove_filter_from_dashboard(
    dashboard_id: int,
    filter_id: str,
    config: RunnableConfig = None,
) -> ToolResult:
    """Remove filter from dashboard. Cascades to all widget bindings.

    Args:
        dashboard_id: Dashboard ID
        filter_id: Filter ID to remove
        config: Runtime config

    Returns:
        JSON tombstone for deleted filter
    """
    runtime = extract_runtime_context(config)
    actor = _actor_ctx(runtime)

    async with app_db_session() as session:
        service = DashboardService.create(tenant_id=actor.tenant_id, db_session=session)
        try:
            await service.remove_filter_for_actor(
                dashboard_id=dashboard_id,
                filter_id=filter_id,
                actor=actor,
            )
            return ToolResult.success({"id": filter_id, "deleted": True})
        except ResourceNotFoundError as e:
            return ToolResult.error_result(code="DASHBOARD_FILTER_NOT_FOUND", message=str(e))
