/**
 * Utilities for detecting and replacing filter parameter references in widget queries.
 */

import type { DashboardFilter, DashboardWidget } from '@/lib/dashboardApi'

/**
 * Get parameter key from a filter.
 * Matches backend validation: paramKey must be provided and valid.
 */
export function getParamKey(filter: DashboardFilter): string {
  return filter.paramKey ?? ''
}

/**
 * Get all parameter names generated by a filter.
 * Mirrors the backend logic in DashboardFilter.get_param_names()
 */
export function getFilterParamNames(filter: DashboardFilter): string[] {
  const baseKey = getParamKey(filter)
  if (filter.type === 'time_range') {
    return [`start_${baseKey}`, `end_${baseKey}`]
  }
  return [baseKey]
}

/**
 * Detect which widgets are affected by a parameter key change.
 *
 * @param oldParamNames - Old parameter names (e.g., ['start_time', 'end_time'])
 * @param allWidgets - All widgets in the dashboard
 * @returns List of widgets that reference any of the old parameters
 */
export function detectAffectedWidgets(
  oldParamNames: string[],
  allWidgets: DashboardWidget[]
): DashboardWidget[] {
  if (oldParamNames.length === 0) {
    return []
  }

  return allWidgets.filter((widget) => {
    const query = widget.query || ''
    // Check if query contains any of the old parameter placeholders
    return oldParamNames.some((param) => {
      // Match :paramName as a word boundary to avoid false matches
      const regex = new RegExp(`:${param}\\b`)
      return regex.test(query)
    })
  })
}

/**
 * Replace parameter names in a query string.
 *
 * @param query - Original query string
 * @param oldParamNames - Old parameter names to find
 * @param newParamNames - New parameter names to replace with (must be same length)
 * @returns New query with parameters replaced
 */
export function replaceParamsInQuery(
  query: string,
  oldParamNames: string[],
  newParamNames: string[]
): string {
  if (oldParamNames.length !== newParamNames.length) {
    throw new Error('oldParamNames and newParamNames must have the same length')
  }

  if (oldParamNames.length === 0) {
    return query
  }

  let result = query
  oldParamNames.forEach((oldParam, idx) => {
    // Match :paramName as word boundary to avoid partial replacements
    const regex = new RegExp(`:${oldParam}\\b`, 'g')
    result = result.replace(regex, `:${newParamNames[idx]}`)
  })
  return result
}

/**
 * Replace parameters in all affected widgets.
 *
 * @param affectedWidgets - Widgets to update
 * @param oldParamNames - Old parameter names
 * @param newParamNames - New parameter names
 * @returns Updated widgets with new parameter names in their queries
 */
export function replaceParamsInWidgets(
  affectedWidgets: DashboardWidget[],
  oldParamNames: string[],
  newParamNames: string[]
): DashboardWidget[] {
  return affectedWidgets.map((widget) => ({
    ...widget,
    query: widget.query
      ? replaceParamsInQuery(widget.query, oldParamNames, newParamNames)
      : widget.query,
  }))
}

/**
 * Get human-readable information about parameter changes.
 */
export function getParamChangeInfo(
  oldParamNames: string[],
  newParamNames: string[]
): { old: string; new: string }[] {
  return oldParamNames.map((oldParam, idx) => ({
    old: `:${oldParam}`,
    new: `:${newParamNames[idx]}`,
  }))
}
